swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  #Proposals---------------------------------------------------------
  /user/accounts: #Endpoint for bank user access to bank accounts
    get: #Get request to find bank user access to bank accounts
      security:
        - Bearer: [] #Authentication expected
      tags:
        - User Module
      summary: User Bank Accounts
      description: Api to get the user's bank accounts
      produces:
        - application/json
      responses:
        '200':
          description: User bank accounts retrieved successully
          schema:
            type: 'array'
            $ref: '#/definitions/Account'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions: #Endpoint for bank user access to bank account transations
    get: #Get request to find bank user access to bank account transations
      security:
        - Bearer: [] #Authentication expected
      tags:
        - User Module
      summary: User Bank Account Transactions
      description: API retrieve user's bank account transactions
      parameters:
        - in: path
          name: accountId
          description: ID of the user's bank account
          required: true
          type: string
        - in: query
          name: page
          description: Page number
          type: integer
        - in: query
          name: limit
          description: Number of transactions on page
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User bank account transactions retrieved successully
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Transaction' # Reference to a single transaction
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}: #Endpoint to get transaction details
    get: #Get request to find transaction details
      security:
        - Bearer: [] #Authentication expected
      tags:
        - User Module
      summary: Transactions Details
      description: API retrieve transaction details of user
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to find
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    patch: # updates transaction details (note and category) without changing the rest of the content
      security:
        - Bearer: [] #Authentication expected
      tags:
        - User Module
      summary: Updating Transaction
      description: API updating notes and categories of a transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updating transaction details
          required: true
          schema:
            $ref: "#/definitions/UpdateTransaction"
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  #------------------------------------------------------------------
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  #Proposals-----------------------------------------------
  UserAccountsResponse:
    type: object
    properties: 
      accounts:
        type: array
        items:
          $ref: '#/definitions/Account'
  UserAccountTransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Account:
    type: object
    properties:
      id:
        type: string
        description: Account ID
      name:
        type: string
        description: Account name
      type:
        type: string
        description: Account type
      balance:
        type: number
        description: Account balance
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Account balance
      transaction type:
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      note:
        type: string
        description: Transaction note
  UpdateTransaction: 
    type: object
    properties:
      category:
        type: string
        description: Updating transaction category
      note:
        type: string
        description: Updating transaction note 
  #--------------------------------------------------------

